### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by madjuju** [Kraego/OpenDTU-Grafana-Stack#2]
[inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "HM400": invalid syntax

**Comment by madjuju** [comment]
same issue
leave empty field "name of the line "
<img width="766" alt="image" src="https://github.com/Kraego/OpenDTU-Grafana-Stack/assets/5285199/36830867-8b8d-4d9f-abaf-6b4dd1da03a0">

**Comment by Kraego** [comment]
You can check the names of the open dtu topics with mqtt explorer - https://github.com/thomasnordquist/MQTT-Explorer or something similiar
